# Generated by Django 3.1.5 on 2021-02-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrrodcutMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('rate_of_interest', models.IntegerField(blank=True, null=True)),
                ('exit_date', models.DateTimeField()),
                ('interest_per_day', models.IntegerField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.IntegerField(default=1, null=True)),
                ('updated_by', models.IntegerField(blank=True, default=None, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Loan.prrodcutmaster')),
            ],
        ),
    ]
