# Generated by Django 3.1.5 on 2021-02-01 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notes', models.CharField(blank=True, max_length=200, null=True)),
                ('TodayRate', models.CharField(blank=True, max_length=50, null=True)),
                ('TodayDate', models.DateTimeField(auto_now_add=True)),
                ('IsonRisk', models.CharField(blank=True, max_length=100, null=True)),
                ('LoanID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='Loan.loaninfo')),
            ],
        ),
    ]
