# Generated by Django 3.1.5 on 2021-02-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0002_loandetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='TodayRate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
