# Generated by Django 3.1.5 on 2021-02-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0004_auto_20210201_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninfo',
            name='sr_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
