# Generated by Django 3.1.5 on 2021-02-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0006_auto_20210203_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='IsonRisk',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
