# Generated by Django 3.1.5 on 2021-02-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0007_auto_20210205_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetail',
            name='UpdateRate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
