# Generated by Django 3.1.5 on 2021-02-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0008_loandetail_updaterate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetail',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
