# Generated by Django 3.1.5 on 2021-03-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0010_auto_20210212_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaninfo',
            name='exit_date',
        ),
    ]
