# Generated by Django 3.1.5 on 2021-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0011_remove_loaninfo_exit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninfo',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
