# Generated by Django 3.1.5 on 2021-03-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0012_loaninfo_exit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninfo',
            name='loan_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
