# Generated by Django 3.1.5 on 2021-03-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0014_auto_20210317_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninfo',
            name='sr_no',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='SerialNo',
        ),
    ]
