# Generated by Django 3.1.5 on 2021-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loan', '0017_auto_20210317_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninfo',
            name='added_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
